
name: Manual trigger
  #Deploys when push is made from the frontend folder

on:
  workflow_dispatch:
  push:
        branches: [ main ]
        paths:
            - "frontend/**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

         
         
    - name: Upload to blob storage
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
            az storage blob upload-batch --account-name azureresumewo -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumeoo" --name "azureresumeoo" --resource-group "AzureResume-rg"

     # Azure logout
    - name: logout
      run: |
        az logout
    if: always()