
name: Manual trigger
  #Deploys when push is made from the frontend folder

on:
  workflow_dispatch:
  push:
        branches: [ main ]
        paths:
            - "frontend/**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
            az storage blob upload-batch --account-name azureresumewo --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode --overwrite -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumeoo" --name "azureresumeoo" --resource-group "AzureResume-rg"

     # Azure logout
    - name: logout
      run: |
        az logout
    if: always()