
name: Manual trigger
  #Deploys when push is made from the frontend folder

on:
  workflow_dispatch:
  push:
        branches: [ main ]
        paths:
            - "frontend/**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v2
      with:
        
        inlineScript: |
       
         az storage blob upload-batch -d azureresumewo-s https://azureresumewo.blob.core.windows.net/$web --pattern "cli-201[89]-??-??.txt"

    - name: Purge CDN endpoint
      uses: azure/CLI@v2
      with:
       
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumeoo" --name "azureresumeoo" --resource-group "AzureResume-rg"
          
     # Azure logout
    - name: logout
      run: |
        az logout
    if: always()